### ISSUE TITLE
Notification buggy

### ISSUE THREAD

**Issue by ghost** [kkkrist/chromium-notifier#45] opened 2022-04-16 12:55 UTC
Hi there and thanks for your work. It's appreciated.
The plugin icon at the toolbar in chromium always shows the "NEW" badge again and again after some minutes/hours, even if there is no update. I click on the icon, but then there is just this for example:

Chromium v100.0.4896.127
Current: v100.0.4896.127
Revision: 1086 (16.4.2022, 00:51:08)
Settings
Last update: 16.4.2022, 14:45:20

... nothing new.

**Comment by kkkrist** [comment] 2022-04-19 09:54
I'm sorry, but I can't reproduce. I'm using exactly the same version of Chromium (mac-stable-ungoogled-marmaduke) and it works fine. 

Are you tracking extension updates? 

Are there any error messages shown in the popup window devtools? (right-click somewhere in the popup window, click "inspect" and select "console" tab)

**Comment by ghost** [comment] 2022-04-19 10:31
Well...
<img width="303" alt="this" src="https://user-images.githubusercontent.com/21237183/163984893-79400145-1c09-4e33-ab05-9c29ab2cbca8.png">
But every time I close Chromium and start it again it says "New" at the icon, and then I click it, see nothing new... the "New" hint is gone, and then appears again after some minutes.

I got Windows 10 19044.1645 x64 btw

No errors at the console in dev tools.

**Comment by kkkrist** [comment] 2022-04-19 12:20
That's really weird. The check interval is [set to 3 hours](https://github.com/kkkrist/chromium-notifier/blob/c54ab813c308f4f77d0e860a076dd47147a67871/js/background.js#L147). I really wonder what's triggering the "New" badge to re-appear after just a few minutes?

I'll try to set up a Windows VM and test with the exact build you're using when I have more time. You could also enable [error tracking](https://github.com/kkkrist/chromium-extension-service#error-tracking) to have the extension send me any errors possibly happening in the background anonymously.

**Comment by ghost** [comment] 2022-04-19 15:25
I enabled error tracking now. Thanks for your work, Sir.

**Comment by emilsimunovic** [comment] 2022-05-23 23:30
I have same problem with win64 Chromium. I get NEW icon notification every hour or so. Even by just clicking settings/enable error tracking the NEW icon will pop. 
![image](https://user-images.githubusercontent.com/49040852/169920543-25324e69-205a-4366-8cf2-eab70a61e3eb.png)

**Comment by ghost** [comment] 2022-05-23 23:45
I uninstalled the plugin some weeks ago. It has no use for me with that bug. It's as good as looking at the release page for a new version after some days.

**Comment by emilsimunovic** [comment] 2022-05-24 00:54
I am sure it is a simple fix, I hope it will be solved soon.

**Comment by kkkrist** [comment] 2022-05-24 09:33
Unfortunately, the error tracker didn't catch anything on that matter yet and I still can't reproduce the problem. I also don't think it's a general issue. The extension still seems to be used by many (error tracker and proxy usage suggest 1000+ users) and there should've been more bug reports like this if it is.

There's just one single call in the whole extension that sets the badge to "New". It's part of the `main()` function that's being run every ~180 mins by a timer and it only sets it to "New" under the following conditions:

- The latest Chromium version available could successfully be fetched from the Woolyss API and the currently running version does not match
- If "Track extension updates" is enabled: The latest versions for currently installed extensions could successfully be fetched from the proxy or the Chrome Web Store API and any one of it does not match what's currently installed.

It's a mystery as to why the "New" badge pops up every few minutes when the timer should only run every 180 minutes.

**Comment by kkkrist** [comment] 2022-05-24 09:38
Here's a debug version that logs these conditions to the console before it sets the badge to "New":

[chromium-notifier-debug.crx.zip](https://github.com/kkkrist/chromium-notifier/files/8761381/chromium-notifier-debug.crx.zip)

After the bug occurs, please go to `chrome://extensions/`, click on "background.html" to open a devtools instance of the extension and tell me what's logged to the console tab!

(Please expand the logged object like this before you take a screenshot or copy/paste:)
<img width="488" alt="Bildschirmfoto 2022-05-24 um 11 40 22" src="https://user-images.githubusercontent.com/3873068/170001924-2bd53c54-dee7-4267-9ad0-3da8ef9f70f0.png">

**Comment by emilsimunovic** [comment] 2022-05-24 22:52
With chromium-notifier-debug.crx I did not get NEW notification at all. I don't understand whay is that. Will test is more for next couple days and also see what happens when actual update landed.

**Comment by emilsimunovic** [comment] 2022-05-25 00:55
Chromium v102.0.5005.63 just landed and chromium-notifier-debug.crx worked how is should. I do not get any error notifications anymore. So what it different between chromium-notifier-debug.crx vs chromium-notifier.crx ?

**Comment by kkkrist** [comment] 2022-05-25 10:46
The difference is really only this one conditional console.log call:

```diff
diff --git a/js/background.js b/js/background.js
index 8baed35..3922072 100644
--- a/js/background.js
+++ b/js/background.js
@@ -129,6 +129,14 @@ chrome.storage.onChanged.addListener(async () => {
 
   const { uaFullVersion } = await getUserAgentData()
 
+  if ((current && uaFullVersion !== current.version) || extensionsNew) {
+    console.log({
+      current,
+      uaFullVersion,
+      extensionsNew
+    })
+  }
+
   chrome.browserAction.setBadgeText({
     text:
       (current && uaFullVersion !== current.version) || extensionsNew
```

This is beyond weird!

If the debug version keeps working, could you try re-installing the last stable version from scratch and see if the problem is gone?

**Comment by emilsimunovic** [comment] 2022-05-25 13:55
This is strange, after re-installing last stable everything seams fine. I have no false NEW icon problems. I will report back if I get it again...

**Comment by kkkrist** [comment] 2022-05-27 13:16
How often do you usually restart Chromium? Does it run for days and weeks on end because you typically only suspend your computer?

**Comment by kkkrist** [comment] 2022-05-27 13:17
@ryder203 Can you try re-installing from scratch and tell if it helps for you too?

**Comment by emilsimunovic** [comment] 2022-05-27 15:35
So far so good. I newer turn of my computer. Restart after update and that's about it.

**Comment by ghost** [comment] 2022-05-27 19:01
> @ryder203 Can you try re-installing from scratch and tell if it helps for you too?

I'm not at home for the next days and if I don't forget it I'll try next week when I'm back on my computer.

**Comment by kkkrist** [comment] 2022-05-31 14:46
Closing for now. I assume this is some weird extension state management issue in upstream. Feel free to re-open if any new info emerges or you find a way to re-produce.

**Closed as completed by kkkrist** 2022-05-31 14:46 UTC
