### ISSUE TITLE
Revision: Invalid Date

### ISSUE THREAD

**Issue by ivan123-tty** [kkkrist/chromium-notifier#42] opened 2021-12-01 14:38 UTC
![image](https://user-images.githubusercontent.com/70339505/144253710-bb11d0fc-675a-4230-9a2d-cacd2f3df7d7.png)

this issue is very similar to #39, but it's not the same issue probs.

i have already triggered the re-fetch and reopened the browser several times. will probably try reinstalling the extension

**Comment by ivan123-tty** [comment] 2021-12-01 14:42
upd: seems like reinstall helped.

**Comment by kkkrist** [comment] 2021-12-01 14:54
Hey,

thanks for bringing it up. I'm glad re-installing helped.

How exactly did you trigger a re-fetch?

Also, did the issue coincide with upgrading Chromium from v95 to v96? (There seems to be some storage incompatibility between these versions, see #41).

**Comment by ivan123-tty** [comment] 2021-12-01 16:15
>
> Hey,
> 
> thanks for bringing it up. I'm glad re-installing helped.
> 
> How exactly did you trigger a re-fetch?
> 
> Also, did the issue coincide with upgrading Chromium from v95 to v96? (There seems to be some storage incompatibility between these versions, see #41).

i just disabled and enabled "track extension updates" setting

**Comment by ivan123-tty** [comment] 2021-12-01 16:16
and no, it didn't coincide with Chromium upgrade; i have updated to Chromium v96 already when i made #41 issue

**Comment by kkkrist** [comment] 2021-12-02 07:56
Oh, you're the one who opened #41 :-) Sorry, didn't look closely enough.

There seem to be others having the same or similar errors. I've checked the error logs and there are a few hundred entries complaining about undefined version too. Unfortunately there are not enough details to pinpoint the issue. I'll have to think about how to log more details without transmitting to much

**Comment by kkkrist** [comment] 2021-12-02 08:09
Oh, I didn't notice you're the same person :-)

The error log has a few hundred entries complaining about undefined version. This might be the same or a related issues. Unfortunately there is not enough detail to find the cause. I'll have to think about how to up the error details without leaking personal info (extensions list).

**Comment by kkkrist** [comment] 2021-12-09 14:24
I now know where the undefined `version` problem comes from, it's unrelated. So closing again. Feel free to reopen if you see it again!

**Closed as completed by kkkrist** 2021-12-09 14:24 UTC
